title: Deepmatics!
description: Exploring AI and a few other interests.
css: /assets/css/style.css
baseurl: "/blog"
plugins:
  - jekyll-seo-tag

collections:
  articles:
    output: true
    permalink: /articles/:title/

# Theme-related directories
layouts_dir: _app/_layouts
includes_dir: _app/_includes
sass:
  sass_dir: _app/_sass

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - .git
  - .jekyll-cache
  - .github
  - vendor
  - node_modules # If you use npm/yarn
  - pages/linkedin-badge.html